# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Chally' do
pod 'AFNetworking', '~> 2.5'
pod 'Facebook-iOS-SDK', '~> 4.1'
pod 'GoogleMaps', '~> 1.10'
pod 'google-plus-ios-sdk', '~> 1.7'
pod 'PureLayout', '~> 2.0'
pod 'Reachability', '~> 3.2'
pod 'SVProgressHUD', '~> 1.1'
pod 'SVPullToRefresh_Bell', '~> 1.0'
end

